//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TabletDemo.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class DemoResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal DemoResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TabletDemo.Resources.DemoResource", typeof(DemoResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cerrar.
        /// </summary>
        internal static string PopupBtnCerrar {
            get {
                return ResourceManager.GetString("PopupBtnCerrar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copiar Texto.
        /// </summary>
        internal static string PopupBtnCopiarTexto {
            get {
                return ResourceManager.GetString("PopupBtnCopiarTexto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Procesando....
        /// </summary>
        internal static string PopupCargandoTexto {
            get {
                return ResourceManager.GetString("PopupCargandoTexto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eventos Recientes.
        /// </summary>
        internal static string PopupLogEventosTitulo {
            get {
                return ResourceManager.GetString("PopupLogEventosTitulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Demo Mobile.
        /// </summary>
        internal static string TitleTabletDemoPage {
            get {
                return ResourceManager.GetString("TitleTabletDemoPage", resourceCulture);
            }
        }
    }
}
